CREATE TABLE CARDS(
            ID INT PRIMARY KEY,
            NAME VARCHAR(255),
            ATTACK INT,
            PROTECTION INT,
            PRICE INT);
CREATE TABLE SETS(
            ID INT PRIMARY KEY,
            NAME VARCHAR(255));
CREATE TABLE SETS_CARDS(
            SETS_ID INT,
            CARDS_ID INT,
            COUNT_CARDS INT
            );

INSERT INTO SETS (ID,NAME) VALUES(1,'BASE') ;

INSERT INTO CARDS 
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (1,'King', 3, 5, 4);
INSERT INTO SETS_CARDS (SETS_ID,CARDS_ID,COUNT_CARDS) VALUES (1,1,2);

INSERT INTO CARDS
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (2,'Queen',4,3,4);
INSERT INTO SETS_CARDS
(SETS_ID,CARDS_ID,COUNT_CARDS)
VALUES (1,2,1);

INSERT INTO CARDS
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (3,'Rook',3,2,3);
INSERT INTO SETS_CARDS
(SETS_ID,CARDS_ID,COUNT_CARDS)
VALUES (1,3,3);

INSERT INTO CARDS
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (4,'Bishop',2,4,3);
INSERT INTO SETS_CARDS
(SETS_ID,CARDS_ID,COUNT_CARDS)
VALUES (1,4,2);

INSERT INTO CARDS
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (5,'Knight',2,1,2);
INSERT INTO SETS_CARDS
(SETS_ID,CARDS_ID,COUNT_CARDS)
VALUES (1,5,3);

INSERT INTO CARDS
(ID,NAME, ATTACK, PROTECTION, PRICE)
VALUES (6,'Pawn',1,1,1);
INSERT INTO SETS_CARDS
(SETS_ID,CARDS_ID,COUNT_CARDS)
VALUES (1,6,5);